config/routes.rb
Rails.application.routes.draw do
  resources :listings
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, :only => [:show]
  resources :cancels, :only => [:index]
  root "listings#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes


  def address_checker
    if (self.street_address || self.state || self.city || self.zip)
      false
    else
      true
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :authenticate_user!
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  #
  # POST /resource
  # def create
  #   super
  # end
  #
  # GET /resource/edit
  # def edit
  #   super
  # end
  #
  # PUT /resource
  # def update
  #   super
  # end
  #
  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :street_address, :city, :state, :zip, :phone, :avatar, :description, :admin]
  end


  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name, :street_address, :city, :state, :zip, :phone, :avatar, :description, :admin]
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #
  # private
  # def configure_sign_up_params
  #   params.require(:user).permit(:first_name, :last_name, :street_address, :city, :state, :zip, :phone, :avatar)
  # end
  #
  # def configure_account_update_params
  #   params.require(:user).permit(:first_name, :last_name, :street_address, :city, :state, :zip, :phone, :avatar)
  # end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show
  end

  def edit
    render :edit
  end

  def update
    if @user.update(user_params)
      flash[:notice]="Updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :street_address, :city, :state, :zip, :phone, :avatar)
  end
end

app/views/users/show.html.erb
<h1 class="page-header text-center">
  Profile for <strong><%= @user.first_name %> <%= @user.last_name %></strong>
</h1>

<div class="row">
  <span style="float: left; margin-right: 20px; margin-bottom: 20px"><%= image_tag @user.avatar.url(:medium) %></span>

<% if current_user != nil %>
  <p>
    Email: <%= @user.email %><br>
    <% if @user.phone == nil && current_user == @user %>
      <br>
      <span class="lead">Please <%= link_to "Add", edit_user_registration_path %> your phone number.</span>
    <% elsif @user.phone == nil && current_user != @user%>
    <% else %>
      Phone: <%= number_to_phone @user.phone %>
    <% end %>
  </p>
  <p>
    <% if @user.address_checker && current_user == @user %>
    <br>
    <span class="lead">Please <%= link_to "Add", edit_user_registration_path %> your address.</span>
    <% elsif @user.address_checker && current_user != @user%>
    <% else %>
    <u>Address:</u><br>
    <%= @user.street_address %><br>
    <%= @user.city %>, <%= @user.state %> <%= @user.zip %>
    <% end %>
  </p>
  <% else %>
    <div style="margin-top: 60px" class="col-md-3 col-md-offset-2 text-center">
      <%= link_to "Login", new_user_session_path, class: "btn btn-lg btn-default inline" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-default inline"  %>
    </div>
  <% end %>
</div>
<div class="row">
  <p>
    <%= @user.description %>
  </p>
</div>

<% if current_user == @user %>
<%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-block btn-default" %>
<% end %>
<hr>
<h1>Listings</h1>


<% @user.listings.in_groups_of(3, false) do |group| %>
  <div class="row">
  <% group.each do |listing| %>
    <%= link_to listing_path(listing) do %>
      <div class="col-md-4">
        <p> <%= image_tag listing.avatars[0].thumb.url %></p>
        <p> <%= listing.title %></p>
        <p> <%= listing.pet_name %></p>
        <p> <%= listing.format_price %></p>
      </div>
    <% end %>
  <% end %>
  </div>
<% end %>