config/routes.rb
Rails.application.routes.draw do
  resources :listings
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users, :only => [:show]
  resources :cancels, :only => [:index]
  root "listings#index"
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-success alert-dismisable text-center alert-custom" role="alert">
  <%= flash[:notice] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="alert alert-danger alert-dismisable text-center alert-custom" role="alert">
  <%= flash[:alert] %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>PetRenter</strong></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a href="/users">Users</a>
        </li>
        <li>
          <form class="navbar-form navbar-left" role="search" action="/">
            <div class="form-group">
              <input type="text" name="query" class="form-control" id="query" placeholder="Search Listings">
            </div>
            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
          </form>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <% if current_user.admin %>
        <li><a>
        Admin
        </a> </li>
        <% end %>
        <li><%= link_to "Add listing", new_listing_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= current_user.email %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <span class="badge badge-warning"><%=  %></span>
          </a>
        </li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetRenter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/flash' %>
<div class="container">

  <%= yield %>
</div>

</body>
</html>